# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefile',
            name='filedbf',
        ),
        migrations.RemoveField(
            model_name='shapefile',
            name='fileprj',
        ),
        migrations.RemoveField(
            model_name='shapefile',
            name='fileqpj',
        ),
        migrations.RemoveField(
            model_name='shapefile',
            name='fileshx',
        ),
        migrations.AddField(
            model_name='shapefile',
            name='shapefileName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
