# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20160411_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgfile',
            name='pathToFileSvg',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
