# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_svgfile_pathtofilesvg'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefile',
            name='layerName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
