# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_shapefile_layername'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgfile',
            name='isOld',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shapefile',
            name='layerName',
            field=models.CharField(choices=[(b'state', b'Staty'), (b'state-by-city', b'Staty skrze hlavni mesta'), (b'region', b'Regiony'), (b'province', b'Provincie'), (b'region_cz', b'Kraje'), (b'region_it', b'Oblasti'), (b'autonomous_Comunity', b'Autonomni spolecenstvi'), (b'bundesland', b'Spolkove zeme'), (b'city', b'Mesta'), (b'city-by-state', b'Hlavni mesta skrze staty'), (b'river', b'Reky'), (b'reservoir', b'Vodni nadrze'), (b'lake', b'Jezera'), (b'sea', b'More'), (b'mountains', b'Pohori'), (b'surface', b'Povrch'), (b'island', b'Ostrovy')], max_length=120, null=True),
        ),
    ]
