# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
